import { z } from "zod";

const glassSchema = z.enum([
  "Highball glass",
  "Cocktail glass",
  "Old-fashioned glass",
  "Whiskey Glass",
  "Collins glass",
  "Pousse cafe glass",
  "Champagne flute",
  "Whiskey sour glass",
  "Cordial glass",
  "Brandy snifter",
  "White wine glass",
  "Nick and Nora Glass",
  "Hurricane glass",
  "Coffee mug",
  "Shot glass",
  "Jar",
  "Irish coffee cup",
  "Punch bowl",
  "Pitcher",
  "Pint glass",
  "Copper Mug",
  "Wine Glass",
  "Beer mug",
  "Margarita/Coupette glass",
  "Beer pilsner",
  "Beer Glass",
  "Parfait glass",
  "Mason jar",
  "Margarita glass",
  "Martini Glass",
  "Balloon Glass",
  "Coupe Glass",
]);

const categorySchema = z.enum([
  "Ordinary Drink",
  "Cocktail",
  "Milk / Float / Shake",
  "Other/Unknown",
  "Cocoa",
  "Shot",
  "Coffee / Tea",
  "Homemade Liqueur",
  "Punch / Party Drink",
  "Beer",
  "Soft Drink / Soda",
]);

const ingredientSchema = z.enum([
  "Light rum",
  "Applejack",
  "Gin",
  "Dark rum",
  "Sweet Vermouth",
  "Strawberry schnapps",
  "Scotch",
  "Apricot brandy",
  "Triple sec",
  "Southern Comfort",
  "Orange bitters",
  "Brandy",
  "Lemon vodka",
  "Blended whiskey",
  "Dry Vermouth",
  "Amaretto",
  "Tea",
  "Champagne",
  "Coffee liqueur",
  "Bourbon",
  "Tequila",
  "Vodka",
  "A\u00f1ejo rum",
  "Bitters",
  "Sugar",
  "Kahlua",
  "demerara Sugar",
  "Dubonnet Rouge",
  "Watermelon",
  "Lime juice",
  "Irish whiskey",
  "Apple brandy",
  "Carbonated water",
  "Cherry brandy",
  "Creme de Cacao",
  "Grenadine",
  "Port",
  "Coffee brandy",
  "Red wine",
  "Rum",
  "Grapefruit juice",
  "Ricard",
  "Sherry",
  "Cognac",
  "Sloe gin",
  "Apple juice",
  "Pineapple juice",
  "Lemon juice",
  "Sugar syrup",
  "Milk",
  "Strawberries",
  "Chocolate syrup",
  "Yoghurt",
  "Mango",
  "Ginger",
  "Lime",
  "Cantaloupe",
  "Berries",
  "Grapes",
  "Kiwi",
  "Tomato juice",
  "Cocoa powder",
  "Chocolate",
  "Heavy cream",
  "Galliano",
  "Peach Vodka",
  "Ouzo",
  "Coffee",
  "Spiced rum",
  "Water",
  "Espresso",
  "Angelica root",
  "Orange",
  "Cranberries",
  "Johnnie Walker",
  "Apple cider",
  "Everclear",
  "Cranberry juice",
  "Egg yolk",
  "Egg",
  "Grape juice",
  "Peach nectar",
  "Lemon",
  "Firewater",
  "Lemonade",
  "Lager",
  "Whiskey",
  "Absolut Citron",
  "Pisco",
  "Irish cream",
  "Ale",
  "Chocolate liqueur",
  "Midori melon liqueur",
  "Sambuca",
  "Cider",
  "Sprite",
  "7-Up",
  "Blackberry brandy",
  "Peppermint schnapps",
  "Creme de Cassis",
  "Mint",
  "Soda water",
  "Angostura bitters",
]);

const drinkSchema = z.object({
  idDrink: z.string(),
  strDrink: z.string(),
  strDrinkAlternate: z.string().nullable(),
  strTags: z.string(),
  strVideo: z.string().nullable(),
  strCategory: categorySchema,
  strIBA: z.enum(["Contemporary Classics", "Unforgettables"]),
  strAlcoholic: z.enum(["Alcoholic", "Non alcoholic", "Optional alcohol"]),
  strGlass: glassSchema,
  strInstructions: z.string(),
  strInstructionsES: z.string().nullable(),
  strInstructionsDE: z.string(),
  strInstructionsFR: z.string().nullable(),
  strInstructionsIT: z.string(),
  "strInstructionsZH-HANS": z.string().nullable(),
  "strInstructionsZH-HANT": z.string().nullable(),
  strDrinkThumb: z.string().url(),
  strIngredient1: ingredientSchema,
  strIngredient2: ingredientSchema,
  strIngredient3: ingredientSchema,
  strIngredient4: ingredientSchema,
  strIngredient5: ingredientSchema.nullable(),
  strIngredient6: ingredientSchema.nullable(),
  strIngredient7: ingredientSchema.nullable(),
  strIngredient8: ingredientSchema.nullable(),
  strIngredient9: ingredientSchema.nullable(),
  strIngredient10: ingredientSchema.nullable(),
  strIngredient11: ingredientSchema.nullable(),
  strIngredient12: ingredientSchema.nullable(),
  strIngredient13: ingredientSchema.nullable(),
  strIngredient14: ingredientSchema.nullable(),
  strIngredient15: ingredientSchema.nullable(),
  strMeasure1: z.string(),
  strMeasure2: z.string(),
  strMeasure3: z.string(),
  strMeasure4: z.string(),
  strMeasure5: z.string().nullable(),
  strMeasure6: z.string().nullable(),
  strMeasure7: z.string().nullable(),
  strMeasure8: z.string().nullable(),
  strMeasure9: z.string().nullable(),
  strMeasure10: z.string().nullable(),
  strMeasure11: z.string().nullable(),
  strMeasure12: z.string().nullable(),
  strMeasure13: z.string().nullable(),
  strMeasure14: z.string().nullable(),
  strMeasure15: z.string().nullable(),
  strImageSource: z.string().url(),
  strImageAttribution: z.string(),
  strCreativeCommonsConfirmed: z.enum(["Yes"]),
  dateModified: z.string(),
});
export type Drink = z.infer<typeof drinkSchema>;

export const lookupResponseSchema = z.object({
  drinks: z.array(drinkSchema),
});
export type LookupResponse = z.infer<typeof lookupResponseSchema>;
