import { z } from "zod";

const glassSchema = z.enum([
  "Highball glass",
  "Cocktail glass",
  "Old-fashioned glass",
  "Whiskey Glass",
  "Collins glass",
  "Pousse cafe glass",
  "Champagne flute",
  "Whiskey sour glass",
  "Cordial glass",
  "Brandy snifter",
  "White wine glass",
  "Nick and Nora Glass",
  "Hurricane glass",
  "Coffee mug",
  "Shot glass",
  "Jar",
  "Irish coffee cup",
  "Punch bowl",
  "Pitcher",
  "Pint glass",
  "Copper Mug",
  "Wine Glass",
  "Beer mug",
  "Margarita/Coupette glass",
  "Beer pilsner",
  "Beer Glass",
  "Parfait glass",
  "Mason jar",
  "Margarita glass",
  "Martini Glass",
  "Balloon Glass",
  "Coupe Glass",
  "Cocktail Glass",
  "Collins Glass",
  "Highball Glass",
  "Coffee Mug",
  "Punch Bowl",
  "Shot Glass",
  "Champagne Flute",
  "Old-Fashioned glass",
]);

const categorySchema = z.enum([
  "Ordinary Drink",
  "Cocktail",
  "Milk / Float / Shake",
  "Other/Unknown",
  "Cocoa",
  "Shot",
  "Coffee / Tea",
  "Homemade Liqueur",
  "Punch / Party Drink",
  "Beer",
  "Soft Drink / Soda",
]);

const drinkSchema = z.object({
  idDrink: z.string(),
  strDrink: z.string(),
  strDrinkAlternate: z.string().nullable(),
  strTags: z.string().nullable(),
  strVideo: z.string().nullable(),
  strCategory: categorySchema,
  strIBA: z
    .enum(["Contemporary Classics", "Unforgettables", "New Era Drinks"])
    .nullable(),
  strAlcoholic: z.enum(["Alcoholic", "Non alcoholic", "Optional alcohol"]),
  strGlass: glassSchema,
  strInstructions: z.string(),
  strInstructionsES: z.string().nullable(),
  strInstructionsDE: z.string().nullable(),
  strInstructionsFR: z.string().nullable(),
  strInstructionsIT: z.string(),
  "strInstructionsZH-HANS": z.string().nullable(),
  "strInstructionsZH-HANT": z.string().nullable(),
  strDrinkThumb: z.string().url(),
  strIngredient1: z.string(),
  strIngredient2: z.string(),
  strIngredient3: z.string().nullable(),
  strIngredient4: z.string().nullable(),
  strIngredient5: z.string().nullable(),
  strIngredient6: z.string().nullable(),
  strIngredient7: z.string().nullable(),
  strIngredient8: z.string().nullable(),
  strIngredient9: z.string().nullable(),
  strIngredient10: z.string().nullable(),
  strIngredient11: z.string().nullable(),
  strIngredient12: z.string().nullable(),
  strIngredient13: z.string().nullable(),
  strIngredient14: z.string().nullable(),
  strIngredient15: z.string().nullable(),
  strMeasure1: z.string().nullable(),
  strMeasure2: z.string().nullable(),
  strMeasure3: z.string().nullable(),
  strMeasure4: z.string().nullable(),
  strMeasure5: z.string().nullable(),
  strMeasure6: z.string().nullable(),
  strMeasure7: z.string().nullable(),
  strMeasure8: z.string().nullable(),
  strMeasure9: z.string().nullable(),
  strMeasure10: z.string().nullable(),
  strMeasure11: z.string().nullable(),
  strMeasure12: z.string().nullable(),
  strMeasure13: z.string().nullable(),
  strMeasure14: z.string().nullable(),
  strMeasure15: z.string().nullable(),
  strImageSource: z.string().url().nullable(),
  strImageAttribution: z.string().nullable(),
  strCreativeCommonsConfirmed: z.enum(["Yes", "No"]),
  dateModified: z.string().nullable(),
});
export type Drink = z.infer<typeof drinkSchema>;

export const lookupResponseSchema = z.object({
  drinks: z.array(drinkSchema).nullable(),
});
export type LookupResponse = z.infer<typeof lookupResponseSchema>;
